# Generated by Django 3.2.18 on 2023-04-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='profile_pic_urls',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='profile_pic',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
