# Generated by Django 3.2.18 on 2023-05-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_appuser_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role_id',
            field=models.IntegerField(),
        ),
    ]
